20181120





seiji@xbnt16:~$ cd myproject
seiji@xbnt16:~/myproject$ ls
git  ref  初期設定



seiji@xbnt16:~/myproject$ python -m venv myenv
seiji@xbnt16:~/myproject$



seiji@xbnt16:~/myproject$ source myenv/bin/activate
(myenv) seiji@xbnt16:~/myproject$ 



dejango install
----------------------------------------------------------------------------
(myenv) seiji@xbnt16:~/myproject$ pip install --upgrade django
Collecting django
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/d1/e5/2676be45ea49cfd0
9a663f289376b3888accd57ff06c953297bfdee1fb08/Django-2.1.3-py3-none-any.whl (
7.3MB)
    100% |████████████████████████████████| 7.3MB 93kB/s 
Collecting pytz (from django)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/f8/0e/2365ddc010afb3d7
9147f1dd544e5ee24bf4ece58ab99b16fbb465ce6dc0/pytz-2018.7-py2.py3-none-any.whl
 (506kB)
    100% |████████████████████████████████| 512kB 683kB/s 
Installing collected packages: pytz, django
Successfully installed django-2.1.3 pytz-2018.7



(pipのupgrade)
----------------------------------------------------------------------------
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(myenv) seiji@xbnt16:~/myproject$ pip install --upgrade pip
Cache entry deserialization failed, entry ignored
Collecting pip
  Using cached https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c
5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl

Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-18.1
(myenv) seiji@xbnt16:~/myproject$ 




---------------------------------------------------------------------------
(myenv) seiji@xbnt16:~/myproject$ pip freeze
Django==2.1.3
pytz==2018.7





mysiteプロジェクト作成
===========================================================================
(myenv) seiji@xbnt16:~/myproject$ django-admin startproject mysite
(myenv) seiji@xbnt16:~/myproject$ 



	/home/seiji/myproject
					|----- mysite
							|---- manage.py
							|---- mysite
									|-----__init.py
									|----- settings.py
									|----- urls.py
									|----- wsgi.py
					


1. settings.py の修正

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

以下に変える
#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['127.0.0.1', '.pythonanywhere.com']




 * defaultのsqlite3をmysqlに変える。
---------------------------------------------------------------------------

default (sqlite3)
# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

* データベースの設定は、ファイルmysqlを見よ。


--------------------------------------------
(mysql)

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'djangoDb',
        'USER': 'seiji01',
        'PASSWORD': 'FLWgar#3$4',
        'HOST': 'localhost',
        'PORT': '',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        'TEST': { 
            'NAME': 'test_djangoDb'
        }
    }
}


*myysql側でdjangoDb, user, password,など作成　(See, mysql file)




(言語) (静的ファイルのパス追加)

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

 
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

--------------------------------------------

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')   <<<< 追加







---------------------------------------------------------------------------
( python manage.py migrate )


(myenv) seiji@xbnt16:~/myproject/mysite$ python manage.py migrate
/home/seiji/myproject/myenv/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (3135, "'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.")
  result = self._query(query)
/home/seiji/myproject/myenv/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (3090, "Changing sql mode 'NO_AUTO_CREATE_USER' is deprecated. It will be removed in a future release.")
  result = self._query(query)
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying sessions.0001_initial... OK
(myenv) seiji@xbnt16:~/myproject/mysite$ 




---------------------------------------------------------------------------
(python manage.py runserver )

(myenv) seiji@xbnt16:~/myproject/mysite$ python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
/home/seiji/myproject/myenv/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (3135, "'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.")
  result = self._query(query)
/home/seiji/myproject/myenv/lib/python3.6/site-packages/pymysql/cursors.py:170: Warning: (3090, "Changing sql mode 'NO_AUTO_CREATE_USER' is deprecated. It will be removed in a future release.")
  result = self._query(query)

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

November 21, 2018 - 16:42:41
Django version 2.1.3, using settings 'mysite.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.


















































